var cards = [
    // handpicked
    {"word": "CAR", "taboo": ["DRIVER","RIDE","TRANSPORT","FAST","TRAVEL"], "source": "handpicked"},
    {"word": "DRAGONFLY", "taboo": ["RED","WINGS","INSECT","FLY","DRAGON"], "source": "handpicked"},
    {"word": "DUCK", "taboo": ["BIRD","YELLOW","CHICKEN","QUACK","FOOD"], "source": "handpicked"},
    {"word": "PILLOW", "taboo": ["HEAD","SLEEP","SOFT","BED","BLANKET"], "source": "handpicked"},
    {"word": "SNOWFLAKE", "taboo": ["COLD","WINTER","FLOWER","SNOW","FALL"], "source": "handpicked"},
    {"word": "HUNGRY", "taboo": ["FEELING","EAT","FOOD","BREAKFAST","MEAL"], "source": "handpicked"},
    {"word": "PROUD", "taboo": ["FEELING","ACCOMPLISH","GREAT","BOAST","HUMBLE"], "source": "handpicked"},
    {"word": "AIRPLANE", "taboo": ["FLY","SKY","PILOT","WINGS","AIRPORT"], "source": "handpicked"},
    {"word": "BEACH", "taboo": ["SAND","OCEAN","SUN","WAVES","VACATION"], "source": "handpicked"},
    {"word": "CHOCOLATE", "taboo": ["SWEET","CANDY","BROWN","COCOA","DESSERT"], "source": "handpicked"},
    {"word": "COMPUTER", "taboo": ["KEYBOARD","SCREEN","MOUSE","INTERNET","TECHNOLOGY"], "source": "handpicked"},
    {"word": "DOCTOR", "taboo": ["MEDICINE","HOSPITAL","NURSE","PATIENT","HEAL"], "source": "handpicked"},
    {"word": "EAGLE", "taboo": ["BIRD","FLY","TALON","FEATHER","BEAK"], "source": "handpicked"},
    {"word": "FOOTBALL", "taboo": ["SPORT","BALL","GOAL","FIELD","TEAM"], "source": "handpicked"},
    {"word": "GUITAR", "taboo": ["INSTRUMENT","STRINGS","MUSIC","PLAY","ACOUSTIC"], "source": "handpicked"},
    {"word": "ICE CREAM", "taboo": ["COLD","SWEET","CONE","DESSERT","FLAVOR"], "source": "handpicked"},
    {"word": "JUNGLE", "taboo": ["FOREST","TREES","ANIMALS","TROPICS","WILD"], "source": "handpicked"},
    {"word": "KANGAROO", "taboo": ["ANIMAL","AUSTRALIA","POUCH","JUMP","MARSUPIAL"], "source": "handpicked"},
    {"word": "LIBRARY", "taboo": ["BOOKS","QUIET","READING","BORROW","STUDY"], "source": "handpicked"},
    {"word": "MOUNTAIN", "taboo": ["TALL","CLIMB","PEAK","HIKE","SUMMIT"], "source": "handpicked"},
    {"word": "PIRATE", "taboo": ["SHIP","TREASURE","SAIL","CAPTAIN","SKULL"], "source": "handpicked"},
    {"word": "MAGICIAN", "taboo": ["MAGIC","TRICKS","ILLUSION","HAT","WAND"], "source": "handpicked"},
    {"word": "OCEAN", "taboo": ["WATER","WAVES","SEA","FISH","BLUE"], "source": "handpicked"},
    {"word": "ROBOT", "taboo": ["MACHINE","METAL","AUTOMATION","AI","FUTURE"], "source": "handpicked"},
    {"word": "SANDWICH", "taboo": ["BREAD","MEAT","LUNCH","CHEESE","EAT"], "source": "handpicked"},
    {"word": "SATELLITE", "taboo": ["SPACE","ORBIT","COMMUNICATION","SIGNAL","DISH"], "source": "handpicked"},
    {"word": "SCISSORS", "taboo": ["CUT", "SHARP", "PAPER", "BLADES", "CRAFT"], "source": "handpicked"},
    {"word": "SNOWMAN", "taboo": ["WINTER", "SNOW", "CARROT", "FROSTY", "COLD"], "source": "handpicked"},
    {"word": "SPACESHIP", "taboo": ["ROCKET", "ASTRONAUT", "SPACE", "FLY", "SHUTTLE"], "source": "handpicked"},
    {"word": "SPIDER", "taboo": ["WEB", "LEGS", "INSECT", "BITE", "CREEPY"], "source": "handpicked"},
    {"word": "SUBMARINE", "taboo": ["UNDERWATER", "NAVY", "DIVE", "TORPEDO", "YELLOW"], "source": "handpicked"},
    {"word": "SUNFLOWER", "taboo": ["YELLOW", "PETALS", "TALL", "SEEDS", "GARDEN"], "source": "handpicked"},
    {"word": "SUPERHERO", "taboo": ["POWERS", "CAPE", "SAVE", "VILLAIN", "COSTUME"], "source": "handpicked"},
    {"word": "SUSHI", "taboo": ["FISH", "RICE", "JAPAN", "ROLL", "SEAWEED"], "source": "handpicked"},
    {"word": "TEACHER", "taboo": ["SCHOOL", "EDUCATE", "CLASSROOM", "STUDENT", "TEACH"], "source": "handpicked"},
    {"word": "TELEPHONE", "taboo": ["CALL", "TALK", "RING", "NUMBER", "DIAL"], "source": "handpicked"},
    {"word": "TELESCOPE", "taboo": ["STARS", "SKY", "LENS", "SPACE", "OBSERVE"], "source": "handpicked"},
    {"word": "TENNIS", "taboo": ["RACKET", "COURT", "BALL", "NET", "SPORT"], "source": "handpicked"},
    {"word": "TIGER", "taboo": ["STRIPES", "JUNGLE", "BIG", "CAT", "ROAR"], "source": "handpicked"},
    {"word": "TRAIN", "taboo": ["TRACKS", "ENGINE", "STATION", "PASSENGER", "RAIL"], "source": "handpicked"},
    {"word": "TROPHY", "taboo": ["WIN", "AWARD", "PRIZE", "COMPETITION", "GOLD"], "source": "handpicked"},
    {"word": "UMBRELLA", "taboo": ["RAIN", "SHADE", "OPEN", "HANDLE", "WET"], "source": "handpicked"},
    {"word": "VAMPIRE", "taboo": ["BLOOD", "NIGHT", "FANGS", "BAT", "COFFIN"], "source": "handpicked"},
    { "word": "LAPTOP", "taboo": ["COMPUTER", "PORTABLE", "KEYBOARD", "SCREEN", "WORK"], "source": "handpicked" },
    { "word": "PIANO", "taboo": ["INSTRUMENT", "KEYS", "MUSIC", "PLAY", "BLACK"], "source": "handpicked" },
    { "word": "POLICE", "taboo": ["LAW", "ARREST", "UNIFORM", "OFFICER", "SAFETY"], "source": "handpicked" },
    { "word": "VOLCANO", "taboo": ["LAVA", "ERUPT", "MOUNTAIN", "ASH", "MAGMA"], "source": "handpicked" },
    { "word": "WHALE", "taboo": ["OCEAN", "BIG", "BLOWHOLE", "SEA", "MAMMAL"], "source": "handpicked" },
    { "word": "WINDOW", "taboo": ["GLASS", "VIEW", "FRAME", "OPEN", "HOUSE"], "source": "handpicked" },
    { "word": "WITCH", "taboo": ["BROOM", "MAGIC", "HAT", "SPELL", "CAULDRON"], "source": "handpicked" },
    { "word": "XYLOPHONE", "taboo": ["INSTRUMENT", "KEYS", "MUSIC", "WOOD", "PLAY"], "source": "handpicked" },
    { "word": "ZEBRA", "taboo": ["STRIPES", "BLACK", "WHITE", "AFRICA", "ANIMAL"], "source": "handpicked" },
    { "word": "ZOO", "taboo": ["ANIMALS", "CAGE", "VISIT", "PARK", "EXHIBIT"], "source": "handpicked" },
    {"word": "UÇAK", "taboo": ["HAVALANMAK","KANAT","GÖKYÜZÜ","HAVAALANI","SEYAHAT"], "source": "handpicked"},
    {"word": "PLAJ", "taboo": ["KUM", "DENİZ", "GÜNEŞ", "DALGA", "TATİL"], "source": "handpicked"},
    {"word": "ÇİKOLATA", "taboo": ["TATLI", "ŞEKER", "SÜTLÜ", "KAKAO", "BİTTER"], "source": "handpicked"},
    {"word": "BİLGİSAYAR", "taboo": ["KLAVYE", "EKRAN", "FARE", "İNTERNET", "TEKNOLOJİ"], "source": "handpicked"},
    {"word": "DOKTOR", "taboo": ["İLAÇ", "HASTANE", "HEMŞİRE", "HASTA", "TEDAVİ"], "source": "handpicked"},
    {"word": "EJDERHA", "taboo": ["MİTOLOJİ", "ATEŞ", "PUL", "KANAT", "FANTASTİK"], "source": "handpicked"},
    {"word": "KARTAL", "taboo": ["KUŞ", "UÇMAK", "PENÇE", "TÜY", "GAGA"], "source": "handpicked"},
    {"word": "FUTBOL", "taboo": ["SPOR", "TOP", "GOL", "SAHA", "TAKIM"], "source": "handpicked"},
    {"word": "GİTAR", "taboo": ["ENSTRÜMAN", "TEL", "MÜZİK", "ÇALMAK", "AKUSTİK"], "source": "handpicked"},
    {"word": "HASTANE", "taboo": ["HASTA", "İLAÇ", "AMELİYAT", "DOKTOR", "HEMŞİRE"], "source": "handpicked"},
    {"word": "DONDURMA", "taboo": ["SOĞUK", "TATLI", "KÜLAH", "YAZ", "VANİLYA"], "source": "handpicked"},
    {"word": "ORMAN", "taboo": ["AĞAÇLAR", "HAYVANLAR", "TROPİK", "VAHŞİ", "YEŞİL"], "source": "handpicked"},
    {"word": "KANGURU", "taboo": ["HAYVAN", "AVUSTRALYA", "KESE", "ZIPLAMAK", "YAVRU"], "source": "handpicked"},
    {"word": "DİZÜSTÜ BİLGİSAYAR", "taboo": ["APPLE", "TAŞINABİLİR", "KLAVYE", "EKRAN", "KÜÇÜK"], "source": "handpicked"},
    {"word": "KÜTÜPHANE", "taboo": ["KİTAP", "SESSİZLİK", "OKUMAK", "ÖDÜNÇ", "DERS"], "source": "handpicked"},
    {"word": "SİHİRBAZ", "taboo": ["GÖSTERİ", "HİLE", "İLLÜZYON", "ŞAPKA", "DEĞNEK"], "source": "handpicked"},
    {"word": "DAĞ", "taboo": ["YÜKSEK", "TIRMANIŞ", "ZİRVE", "YÜRÜYÜŞ", "EVEREST"], "source": "handpicked"},
    {"word": "OKYANUS", "taboo": ["SU", "DALGA", "DENİZ", "BALIK", "MAVİ"], "source": "handpicked"},
    {"word": "PİYANO", "taboo": ["ENSTRÜMAN", "TUŞ", "MÜZİK", "ÇALMAK", "SİYAH"], "source": "handpicked"},
    {"word": "KORSAN", "taboo": ["GEMİ", "HAZİNE", "YELKEN", "KAPTAN", "HIRSIZ"], "source": "handpicked"},
    {"word": "POLİS", "taboo": ["KANUN", "TUTUKLAMAK", "ÜNİFORMA", "MEMUR", "GÜVENLİK"], "source": "handpicked"},
    {"word": "ROBOT", "taboo": ["MAKİNE", "METAL", "OTOMASYON", "YAPAY ZEKA", "GELECEK"], "source": "handpicked"},
    {"word": "SANDVİÇ", "taboo": ["EKMEK", "DOMATES", "KAHVALTI", "PEYNİR", "ÇAY"], "source": "handpicked"},
    {"word": "UYDU", "taboo": ["UZAY", "YÖRÜNGE", "İLETİŞİM", "SİNYAL", "ÇANAK"], "source": "handpicked"},
    {"word": "MAKAS", "taboo": ["KESMEK", "KESKİN", "KAĞIT", "BIÇAK", "EL SANATI"], "source": "handpicked"},
    {"word": "KARDAN ADAM", "taboo": ["KIŞ", "KAR", "HAVUÇ", "SOĞUK", "ZEYTİN"], "source": "handpicked"},
    {"word": "UZAY GEMİSİ", "taboo": ["ROKET", "ASTRONOT", "ELON MUSK", "UÇMAK", "MEKİK"], "source": "handpicked"},
    {"word": "ÖRÜMCEK", "taboo": ["AĞ", "AVUSTRALYA", "BÖCEK", "ISIRIK", "FOBİ"], "source": "handpicked"},
    {"word": "DENİZALTI", "taboo": ["SU", "DONANMA", "DALIŞ", "TORPİDO", "ASKERİ"], "source": "handpicked"},
    {"word": "AYÇİÇEĞİ", "taboo": ["SARI", "GÜNEŞ", "DÖNMEK", "TOHUM", "BAHÇE"], "source": "handpicked"},
    {"word": "SÜPER KAHRAMAN", "taboo": ["GÜÇ", "PELERİN", "KURTARMAK", "KÖTÜ ADAM", "KOSTÜM"], "source": "handpicked"},
    {"word": "SUŞİ", "taboo": ["BALIK", "PİRİNÇ", "JAPON", "RULO", "YOSUN"], "source": "handpicked"},
    {"word": "ÖĞRETMEN", "taboo": ["OKUL", "EĞİTMEK", "SINIF", "ÖĞRENCİ", "DERS"], "source": "handpicked"},
    {"word": "TELEFON", "taboo": ["ARAMAK", "KONUŞMAK", "ÇALMAK", "NUMARA", "ÇEVİRME"], "source": "handpicked"},
    {"word": "TELESKOP", "taboo": ["YILDIZ", "GÖKYÜZÜ", "MERCEK", "UZAY", "GÖZLEM"], "source": "handpicked"},
    {"word": "TENİS", "taboo": ["RAKET", "KORT", "TOP", "AĞ", "SPOR"], "source": "handpicked"},
    {"word": "KAPLAN", "taboo": ["ÇİZGİLİ", "ORMAN", "BÜYÜK", "KEDİ", "KÜKREME"], "source": "handpicked"},
    {"word": "TREN", "taboo": ["RAY", "MOTOR", "İSTASYON", "YOLCU", "DEMİRYOLU"], "source": "handpicked"},
    {"word": "KUPA", "taboo": ["KAZANMAK", "ÖDÜL", "BİRİNCİ", "YARIŞMA", "ALTIN"], "source": "handpicked"},
    {"word": "ŞEMSİYE", "taboo": ["YAĞMUR", "GÖLGE", "AÇMAK", "SAP", "ISLAK"], "source": "handpicked"},
    {"word": "VAMPİR", "taboo": ["KAN", "GECE", "DİŞ", "YARASA", "TABUT"], "source": "handpicked"},
    {"word": "VOLKAN", "taboo": ["LAV", "PATLAMA", "DAĞ", "KÜL", "KONAK"], "source": "handpicked"},
    {"word": "BALİNA", "taboo": ["OKYANUS", "BÜYÜK", "BEYAZ", "DENİZ", "MEMELİ"], "source": "handpicked"},
    {"word": "PENCERE", "taboo": ["CAM", "PERDE", "ÇERÇEVE", "AÇMAK", "EV"], "source": "handpicked"},
    {"word": "CADI", "taboo": ["SÜPÜRGE", "SİHİR", "ŞAPKA", "BÜYÜ", "KAZAN"], "source": "handpicked"},
    {"word": "FLÜT", "taboo": ["ENSTRÜMAN", "OKUL", "MÜZİK", "DELİK", "ÇALMAK"], "source": "handpicked"},
    {"word": "ZEBRA", "taboo": ["ÇİZGİLİ", "SİYAH", "BEYAZ", "AFRİKA", "HAYVAN"], "source": "handpicked"},
    {"word": "HAYVANAT BAHÇESİ", "taboo": ["ÇOCUK", "KAFES", "ZİYARET", "PARK", "SERGİ"], "source": "handpicked"}
];