var cards = [
    // handpicked
    {"word": "CAR", "taboo": ["DRIVER","RIDE","TRANSPORT","FAST","TRAVEL"], "source": "handpicked"},
    {"word": "DRAGONFLY", "taboo": ["RED","WINGS","INSECT","FLY","DRAGON"], "source": "handpicked"},
    {"word": "DUCK", "taboo": ["BIRD","YELLOW","CHICKEN","QUACK","FOOD"], "source": "handpicked"},
    {"word": "PILLOW", "taboo": ["HEAD","SLEEP","SOFT","BED","BLANKET"], "source": "handpicked"},
    {"word": "SNOWFLAKE", "taboo": ["COLD","WINTER","FLOWER","SNOW","FALL"], "source": "handpicked"},
    {"word": "HUNGRY", "taboo": ["FEELING","EAT","FOOD","BREAKFAST","MEAL"], "source": "handpicked"},
    {"word": "PROUD", "taboo": ["FEELING","ACCOMPLISH","GREAT","BOAST","HUMBLE"], "source": "handpicked"},
    {"word": "AIRPLANE", "taboo": ["FLY","SKY","PILOT","WINGS","AIRPORT"], "source": "handpicked"},
    {"word": "BEACH", "taboo": ["SAND","OCEAN","SUN","WAVES","VACATION"], "source": "handpicked"},
    {"word": "CHOCOLATE", "taboo": ["SWEET","CANDY","BROWN","COCOA","DESSERT"], "source": "handpicked"},
    {"word": "COMPUTER", "taboo": ["KEYBOARD","SCREEN","MOUSE","INTERNET","TECHNOLOGY"], "source": "handpicked"},
    {"word": "DOCTOR", "taboo": ["MEDICINE","HOSPITAL","NURSE","PATIENT","HEAL"], "source": "handpicked"},
    {"word": "EAGLE", "taboo": ["BIRD","FLY","TALON","FEATHER","BEAK"], "source": "handpicked"},
    {"word": "FOOTBALL", "taboo": ["SPORT","BALL","GOAL","FIELD","TEAM"], "source": "handpicked"},
    {"word": "GUITAR", "taboo": ["INSTRUMENT","STRINGS","MUSIC","PLAY","ACOUSTIC"], "source": "handpicked"},
    {"word": "ICE CREAM", "taboo": ["COLD","SWEET","CONE","DESSERT","FLAVOR"], "source": "handpicked"},
    {"word": "JUNGLE", "taboo": ["FOREST","TREES","ANIMALS","TROPICS","WILD"], "source": "handpicked"},
    {"word": "KANGAROO", "taboo": ["ANIMAL","AUSTRALIA","POUCH","JUMP","MARSUPIAL"], "source": "handpicked"},
    {"word": "LIBRARY", "taboo": ["BOOKS","QUIET","READING","BORROW","STUDY"], "source": "handpicked"},
    {"word": "MOUNTAIN", "taboo": ["TALL","CLIMB","PEAK","HIKE","SUMMIT"], "source": "handpicked"},
    {"word": "PIRATE", "taboo": ["SHIP","TREASURE","SAIL","CAPTAIN","SKULL"], "source": "handpicked"},
    {"word": "MAGICIAN", "taboo": ["MAGIC","TRICKS","ILLUSION","HAT","WAND"], "source": "handpicked"},
    {"word": "OCEAN", "taboo": ["WATER","WAVES","SEA","FISH","BLUE"], "source": "handpicked"},
    {"word": "ROBOT", "taboo": ["MACHINE","METAL","AUTOMATION","AI","FUTURE"], "source": "handpicked"},
    {"word": "SANDWICH", "taboo": ["BREAD","MEAT","LUNCH","CHEESE","EAT"], "source": "handpicked"},
    {"word": "SATELLITE", "taboo": ["SPACE","ORBIT","COMMUNICATION","SIGNAL","DISH"], "source": "handpicked"},
    {"word": "SCISSORS", "taboo": ["CUT", "SHARP", "PAPER", "BLADES", "CRAFT"], "source": "handpicked"},
    {"word": "SNOWMAN", "taboo": ["WINTER", "SNOW", "CARROT", "FROSTY", "COLD"], "source": "handpicked"},
    {"word": "SPACESHIP", "taboo": ["ROCKET", "ASTRONAUT", "SPACE", "FLY", "SHUTTLE"], "source": "handpicked"},
    {"word": "SPIDER", "taboo": ["WEB", "LEGS", "INSECT", "BITE", "CREEPY"], "source": "handpicked"},
    {"word": "SUBMARINE", "taboo": ["UNDERWATER", "NAVY", "DIVE", "TORPEDO", "YELLOW"], "source": "handpicked"},
    {"word": "SUNFLOWER", "taboo": ["YELLOW", "PETALS", "TALL", "SEEDS", "GARDEN"], "source": "handpicked"},
    {"word": "SUPERHERO", "taboo": ["POWERS", "CAPE", "SAVE", "VILLAIN", "COSTUME"], "source": "handpicked"},
    {"word": "SUSHI", "taboo": ["FISH", "RICE", "JAPAN", "ROLL", "SEAWEED"], "source": "handpicked"},
    {"word": "TEACHER", "taboo": ["SCHOOL", "EDUCATE", "CLASSROOM", "STUDENT", "TEACH"], "source": "handpicked"},
    {"word": "TELEPHONE", "taboo": ["CALL", "TALK", "RING", "NUMBER", "DIAL"], "source": "handpicked"},
    {"word": "TELESCOPE", "taboo": ["STARS", "SKY", "LENS", "SPACE", "OBSERVE"], "source": "handpicked"},
    {"word": "TENNIS", "taboo": ["RACKET", "COURT", "BALL", "NET", "SPORT"], "source": "handpicked"},
    {"word": "TIGER", "taboo": ["STRIPES", "JUNGLE", "BIG", "CAT", "ROAR"], "source": "handpicked"},
    {"word": "TRAIN", "taboo": ["TRACKS", "ENGINE", "STATION", "PASSENGER", "RAIL"], "source": "handpicked"},
    {"word": "TROPHY", "taboo": ["WIN", "AWARD", "PRIZE", "COMPETITION", "GOLD"], "source": "handpicked"},
    {"word": "UMBRELLA", "taboo": ["RAIN", "SHADE", "OPEN", "HANDLE", "WET"], "source": "handpicked"},
    {"word": "VAMPIRE", "taboo": ["BLOOD", "NIGHT", "FANGS", "BAT", "COFFIN"], "source": "handpicked"} ];
//     {"word": "ARTIFICIAL INTELLIGENCE", "taboo": ["COMPUTER","ROBOT","SCIENCE","MACHINE LEARNING","DECISIONS"], "source": "handcrafted"},
//     {"word": "DATASET", "taboo": ["INFORMATION","RECORDS","MODEL","TRAINING","TEST"], "source": "handcrafted"},
//     {"word": "RESNET", "taboo": ["COMPUTER VISION","IMAGENET","SKIP CONNECTIONS","GRADIENT VANISHING","NEURAL NETWORK"], "source": "handcrafted"},
//     {"word": "MONTEZUMA REVENGE", "taboo": ["REINFORCEMENT LEARNING","GAME","ATARI","PLANNING","AZTECS"], "source": "handcrafted"},
//     {"word": "EPOCH", "taboo": ["OBSERVATION","DATASET","TRAINING","MACHINE LEARNING","TIME"], "source": "handcrafted"},
//     {"word": "SIMULATION", "taboo": ["IMITATION","GENERATED","DATA","MODEL","COMPUTER"], "source": "handcrafted"},
//     {"word": "ROBOT", "taboo": ["MACHINE","COMPUTER","AUTOMATIC","ACTIONS","TASKS"], "source": "handcrafted"},
//     {"word": "SOFTWARE", "taboo": ["COMPUTER","HARDWARE","PROGRAM","APPLICATION","CODE"], "source": "handcrafted"},
//     {"word": "EXPLORATION", "taboo": ["ENVIRONMENT","INFORMATION","AGENT","DATA","EXPOTATION"], "source": "handcrafted"},
//     {"word": "CHATBOT", "taboo": ["ARTIFICIAL INTELLIGENCE","CONVERSATION","TALKING","TEXT","COMPUTER PROGRAM"], "source": "handcrafted"},
//     {"word": "CLUSTERING", "taboo": ["SIMILARITY","FEATURES","DATA","UNSUPERVISED LEARNING","GROUPS"], "source": "handcrafted"},
//     {"word": "BAYESIAN NETWORK", "taboo": ["PROBABILITY","UNCERTAINTY","STATISTICAL MODEL","DISTRIBUTION","NODES"], "source": "handcrafted"},
//     {"word": "WORD2VEC", "taboo": ["WORD EMBEDDING","TOMAS MIKOLOV","TEXT","NLP","NEURAL NETWORK"], "source": "handcrafted"},
//     {"word": "VECTOR", "taboo": ["DIMENSION","NUMBER","LIST","COORDINATE","SPACE"], "source": "handcrafted"},
//     {"word": "COMPUTER VISION", "taboo": ["IMAGE RECOGNITION","PICTURE","MACHINE LEARNING","CNNS","OBJECTS"], "source": "handcrafted"},
//     {"word": "OUTLIER", "taboo": ["DIFFERENT","ANOMALY","DETECTION","ERROR","RARE"], "source": "handcrafted"},
//     {"word": "TRANSFORMERS", "taboo": ["ATTENTION","encoder-decoder","NLP","GPT MODELS","BERT"], "source": "handcrafted"},
//     {"word": "BREAKOUT", "taboo": ["BALL","ATARI","GAME","DQN","reinforcement learning"], "source": "handcrafted"},
//     {"word": "K-NN", "taboo": ["SPACE","lazy learning","DISTANCE","SIMILARITY","INSTANCE"], "source": "handcrafted"},
//     {"word": "DEEP BLUE", "taboo": ["CHESS","Garri Kasparow","IBM","TREE SEARCH","AI"], "source": "handcrafted"},
//     {"word": "MECHANICAL TURK", "taboo": ["CHESS GAME","ANNOTATION","DATA","HANDMADE","HUMAN"], "source": "handcrafted"},
//     {"word": "WALL-E", "taboo": ["ROBOT","DISNEY PIXAR","CLEANING","MOVIE","COSMOS"], "source": "handcrafted"},
//     {"word": "TESLA", "taboo": ["NICOLA","ELON MASK","CARS","AI","STOCKS"], "source": "handcrafted"},
//     {"word": "ARXIV", "taboo": ["RESEARCH","PRE-PRINTS","WEBSITE","CORNELL UNIVERSITY","ARTICLES"], "source": "handcrafted"},
//     {"word": "SUPERVISED LEARNING", "taboo": ["TRAINING","FUNCTION","ALGORITHM","BIAS VARIANCE","RISK MINIMIZATION"], "source": "AI generated"},
//     {"word": "SPEECH RECOGNITION", "taboo": ["VOICE","SPEAKER","SYSTEM","WORD","SOUND"], "source": "AI generated"},
//     {"word": "CORRELATION DOES NOT IMPLY CAUSATION", "taboo": ["FALLACY","CAUSE EFFECT","CAUSALITY","WINDMILL","EXAMPLE"], "source": "AI generated"},
//     {"word": "WOLFRAM MATHEMATICA", "taboo": ["TOOL","LANGUAGE","DATA","CODE","NOTEBOOK"], "source": "AI generated"},
//     {"word": "OPTICAL CHARACTER RECOGNITION", "taboo": ["FONT","GLYPH","TEXT","IMAGE","DOCUMENT"], "source": "AI generated"},
//     {"word": "QUEUEING THEORY", "taboo": ["CUSTOMER","JOB","SERVICE","NETWORK","NODE"], "source": "AI generated"},
//     {"word": "EXPERIMENT", "taboo": ["RESULT","TREATMENT","HYPOTHESIS","CONTROL","STUDY"], "source": "AI generated"},
//     {"word": "MARKOV CHAIN", "taboo": ["TRANSITION","STATE SPACE","TIME","PROCESS","PROBABILITY"], "source": "AI generated"},
//     {"word": "SUPPORT VECTOR MACHINE", "taboo": ["MARGIN","HYPERPLANE","KERNEL","CLASSIFIER","SVMS"], "source": "AI generated"},
//     {"word": "REINFORCEMENT LEARNING", "taboo": ["POLICY","ACTION VALUE","AGENT","METHOD","STATE ACTION"], "source": "AI generated"},
//     {"word": "NAIVE BAYES CLASSIFIER", "taboo": ["PROBABILITY","FEATURE","DOCUMENT","EVENT MODEL","CLASSIFICATION"], "source": "AI generated"},
//     {"word": "LINEAR CLASSIFIER", "taboo": ["TRAINING","VECTOR","LOSS","OUTPUT","FUNCTION"], "source": "AI generated"},
//     {"word": "PATTERN RECOGNITION", "taboo": ["LABEL","ALGORITHM","FEATURE","DATA","OUTPUT"], "source": "AI generated"},
//     {"word": "PERCEPTRON", "taboo": ["WEIGHT","ALGORITHM","LAYER","INPUT VECTOR","TRAINING"], "source": "AI generated"},
//     {"word": "OVERFITTING", "taboo": ["MODEL","DATA","FUNCTION","REGRESSION","PARAMETER"], "source": "AI generated"},
//     {"word": "HANDWRITING RECOGNITION", "taboo": ["CHARACTER","PDA","SYSTEM","LINE","TABLET"], "source": "AI generated"},
//     {"word": "EARLY STOPPING", "taboo": ["VALIDATION","REGULARIZATION","TRAINING","ITERATION","LEARNER"], "source": "AI generated"},
//     {"word": "MACHINE LEARNING", "taboo": ["DATA","MODEL","TRAINING","BIAS","ALGORITHM"], "source": "AI generated"},
//     {"word": "FEATURE EXTRACTION", "taboo": ["DETECTION","DIMENSIONALITY REDUCTION","ANALYSIS","IMAGE","DATA"], "source": "AI generated"},
//     {"word": "TEXT MINING", "taboo": ["ANALYSIS","ANALYTICS","COPYRIGHT","BUSINESS","DOCUMENT"], "source": "AI generated"},
//     {"word": "QUESTION ANSWERING", "taboo": ["QA SYSTEM","ANSWER TYPE","DOMAIN","DOCUMENT","KNOWLEDGE"], "source": "AI generated"},
//     {"word": "R PROGRAMMING LANGUAGE", "taboo": ["PACKAGE","USER","CRAN","DATA","SOFTWARE"], "source": "AI generated"},
//     {"word": "TIME SERIES", "taboo": ["ANALYSIS","DATA","CHART","INTERPOLATION","MODEL"], "source": "AI generated"},
//     {"word": "LOSS FUNCTION", "taboo": ["DECISION RULE","VALUE","FREQUENTIST","RISK","UTILITY"], "source": "AI generated"},
//     {"word": "DIMENSIONALITY REDUCTION", "taboo": ["SPACE","KERNEL","DATA","TECHNIQUE","NMF"], "source": "AI generated"},
//     {"word": "FACIAL RECOGNITION SYSTEM", "taboo": ["FACE","PRIVACY","TECHNOLOGY","POLICE","IMAGE"], "source": "AI generated"},
//     {"word": "PART-OF-SPEECH TAGGING", "taboo": ["WORD","CORPUS","PO TAGGER","VERB","NOUN"], "source": "AI generated"},
//     {"word": "CURSE OF DIMENSIONALITY", "taboo": ["HYPERCUBE","DISTANCE FUNCTION","DATA","SPACE","NEIGHBOR"], "source": "AI generated"},
//     {"word": "N-GRAM", "taboo": ["SEQUENCE","LANGUAGE MODEL","PROBABILITY WORD","LETTER","SERVE"], "source": "AI generated"},
//     {"word": "Q-LEARNING", "taboo": ["REWARD","ACTION","STATE","VALUE","REINFORCEMENT"], "source": "AI generated"},
//     {"word": "BACKPROPAGATION", "taboo": ["OUTPUT","WEIGHT","ERROR","NETWORK","NEURON"], "source": "AI generated"},
//     {"word": "STATISTICAL CLASSIFICATION", "taboo": ["CLASSIFIER","OBSERVATION","CATEGORY","INSTANCE","PROCEDURE"], "source": "AI generated"},
//     {"word": "CROSS ENTROPY", "taboo": ["DISTRIBUTION","DIVERGENCE","SET","PROBABILITY OUTCOME","LIKELIHOOD"], "source": "AI generated"},
//     {"word": "MULTI-ARMED BANDIT", "taboo": ["REWARD","STRATEGY","LEVER","EXPLOITATION","PROBLEM"], "source": "AI generated"},
//     {"word": "PERPLEXITY", "taboo": ["TEST SAMPLE","BIT","PROBABILITY","WORD","DISTRIBUTION"], "source": "AI generated"},
//     {"word": "SOFTMAX FUNCTION", "taboo": ["VALUE","SIGMOID","INPUT","TEMPERATURE","PROBABILITY"], "source": "AI generated"},
//     {"word": "AUTOENCODER", "taboo": ["LAYER","INPUT","REPRESENTATION","ACTIVATION","PRETRAINING"], "source": "AI generated"},
//     {"word": "IRIS FLOWER DATA SET", "taboo": ["SPECIE","VIRGINICA VERSICOLOR","FISHER","LENGTH WIDTH","NODE"], "source": "AI generated"},
//     {"word": "LONG SHORT-TERM MEMORY", "taboo": ["UNIT","CELL","FORGET GATE","RNN","Jürgen Schmidhuber"], "source": "AI generated/handmade"},
//     {"word": "BAG-OF-WORDS MODEL", "taboo": ["DOCUMENT","TERM FREQUENCY","TEXT","REPRESENTATION","SPAM"], "source": "AI generated"},
//     {"word": "ANDREW NG", "taboo": ["STANFORD","COURSERA","HELICOPTER","STUDENT","GOOGLE BRAIN"], "source": "AI generated"},
//     {"word": "PAGERANK", "taboo": ["GOOGLE","LINK PAGE","PATENT","SEARCH","SURFER"], "source": "AI generated"},
//     {"word": "KAGGLE", "taboo": ["DATA SCIENCE","MACHINE COMPETITION","COMMUNITY","DATA SCIENTIST","MARCH"], "source": "AI generated"},
//     {"word": "CONVOLUTIONAL NEURAL NETWORK", "taboo": ["LAYER","NEURON","IMAGE","CNNS","INPUT"], "source": "AI generated"},
//     {"word": "GOOGLE BRAIN", "taboo": ["TEAM","RESOLUTION PICTURE","NETWORK","SYSTEM","ENCRYPTION"], "source": "AI generated"},
//     {"word": "DEEPMIND", "taboo": ["GAME","GOOGLE","COMPANY","HOSPITAL","AI"], "source": "AI generated"},
//     {"word": "WORD EMBEDDING", "taboo": ["EMBEDDINGS","VECTOR SPACE","REPRESENTATION","SEQUENCE","FASTTEXT"], "source": "AI generated"},
//     {"word": "DEEPDREAM", "taboo": ["IMAGE","NETWORK","TEXTURE","MORDVINTSEV","USAGE ACTIVITY"], "source": "AI generated"},
//     {"word": "ALPHAGO", "taboo": ["GAME","PLAYER","MATCH","MOVE","LEE"], "source": "AI generated"},
//     {"word": "PRISMA APP", "taboo": ["MOISEENKOV","JULY","STYLE TRANSFER","STORE","DOWNLOADS"], "source": "AI generated"},
//     {"word": "KERAS", "taboo": ["CHOLLET","BACKEND","HOST TOOL IMAGE","STANDALONE MACHINE LEARNING","FRAMEWORK LEVEL SET"], "source": "AI generated"},
//     {"word": "OPENAI FIVE", "taboo": ["GAME","BOT","ACTION","PLAYER","DOTA"], "source": "AI generated"},
// ];